import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ToastContainer} from "react-toastify";
import {AuthenticationProvider} from "@/contexts/app.context";

import SocketWrapper from "@/components/SocketWrapper";
const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthenticationProvider>
					<SocketWrapper>
						{children}
						<div id="photo-picker-element"></div>
					</SocketWrapper>
				</AuthenticationProvider>

				<ToastContainer
					position="top-right"
					autoClose={2000}
					hideProgressBar={false}
					newestOnTop={false}
					closeOnClick
					rtl={false}
					pauseOnFocusLoss
					draggable
					pauseOnHover
					theme="light"
				/>
			</body>
		</html>
	);
}
